name: Monitoring Tests

on:
  push:
    paths:
      - 'services/monitoring.ts'
      - 'scripts/test-monitoring.ts'
      - '__tests__/services/monitoring.test.ts'
  pull_request:
    paths:
      - 'services/monitoring.ts'
      - 'scripts/test-monitoring.ts'
      - '__tests__/services/monitoring.test.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Make test script executable
      run: chmod +x scripts/test-monitoring.ts
      
    - name: Run monitoring tests
      run: npm run test:monitoring
      
    - name: Run monitoring unit tests
      run: npm run test -- __tests__/services/monitoring.test.ts
